.PHONY: all clean

BUILD_TMPDIR ?= /tmp
CMAKE_ARGS := -DCMAKE_BUILD_TYPE=Release
ifeq ($(CUDA),1)
ifeq ($(HIP),1)
$(error Set at most one of CUDA=1 or HIP=1)
endif
endif
ifeq ($(CUDA),1)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_ENABLE_CUDA=ON
CUDA_ARCHS ?= 90
THREADS_PER_BLOCK ?= 128
MAXREGCOUNT ?= 255
FMA ?= 0
CMAKE_ARGS += -DCMAKE_CUDA_ARCHITECTURES=$(CUDA_ARCHS)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_THREADS_PER_BLOCK=$(THREADS_PER_BLOCK)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_MAXREGCOUNT=$(MAXREGCOUNT)
ifeq ($(FMA),1)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_FMA=ON
else
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_FMA=OFF
endif
else
ifeq ($(HIP),1)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_ENABLE_HIP=ON
HIP_ARCHS ?= gfx90a
THREADS_PER_BLOCK ?= 128
CMAKE_ARGS += -DCMAKE_HIP_ARCHITECTURES=$(HIP_ARCHS)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_THREADS_PER_BLOCK=$(THREADS_PER_BLOCK)
else
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_ENABLE_CUDA=OFF
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_ENABLE_HIP=OFF
endif
endif

all:
	TMPDIR=$(BUILD_TMPDIR) cmake -S . -B build $(CMAKE_ARGS)
	TMPDIR=$(BUILD_TMPDIR) cmake --build build -j

clean:
	cmake -E rm -rf build
