.PHONY: all clean

BUILD_TMPDIR ?= /tmp
CMAKE_ARGS := -DCMAKE_BUILD_TYPE=Release
ifeq ($(CUDA),1)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_ENABLE_CUDA=ON
CUDA_ARCHS ?= 90
THREADS_PER_BLOCK ?= 128
MAXREGCOUNT ?= 255
FMA ?= 0
CMAKE_ARGS += -DCMAKE_CUDA_ARCHITECTURES=$(CUDA_ARCHS)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_THREADS_PER_BLOCK=$(THREADS_PER_BLOCK)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_MAXREGCOUNT=$(MAXREGCOUNT)
ifeq ($(FMA),1)
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_FMA=ON
else
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_CUDA_FMA=OFF
endif
else
CMAKE_ARGS += -DPRIMORDIAL_ROS2S_ENABLE_CUDA=OFF
endif

all:
	TMPDIR=$(BUILD_TMPDIR) cmake -S . -B build $(CMAKE_ARGS)
	TMPDIR=$(BUILD_TMPDIR) cmake --build build -j

clean:
	cmake -E rm -rf build
